### ISSUE TITLE
The link to the addon on `addons.mozilla.org` is invalid

### ISSUE THREAD

**Issue by Colburse** [d3vr/yt-siphon#2]
https://addons.mozilla.org/en-US/firefox/addon/yt-siphon/

**Comment by d3vr** [comment]
It's because I got it signed and published today and from what I understand it can take up to a day? This is the first add-on I publish on AMO so I'm not perfectly sure.

**Comment by 3052** [comment]
as a workaround the XPI is here:

https://github.com/d3vr/yt-siphon/releases/tag/v1.0.5-2

**Comment by d3vr** [comment]
It was reviewed and approved, can now be obtained through the [Add-Ons store](https://addons.mozilla.org/en-US/firefox/addon/yt-siphon/) 🥳

**Comment by ZekDtonik** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
netqqnet, @xhgh, @Mc01, @stlcours, @talaatmagdyx, @Galiold, @jackbback, @tzw5099, @Ruggiero-Santo, @lATAl, @seebigsea, @phiresky, @NullpointerWorks, @viaNull, @ysono, @tiero, @Asura-one, @ycwei5, @Roughman007, @framboise-pi, @PEMTR, @Andrysky, @GayHubUser, @axiom215, @huyz97, @renanoliveira0, @fabiohl, @NEWCREATOR1159, @thdaraujo, @theunixbeard, @hbakhtiyor, @ziplus4, @nedmarinov, @ciphersaw, @robofearth, @heyauri, @1997von, @0oVicero0, @aveekbhat, @forestbird, @dorapocket, @chmac, @huohuoyu, @SuperITMan, @lnzhaotian, @jkdlgy, @famorai, @otzy007, @shobrook, @expfun
